"""Add ON DELETE CASCADE to user_tracked_products

Revision ID: 7f100df8822b
Revises: 330213fbaf08
Create Date: 2025-10-05 00:32:22.418335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f100df8822b'
down_revision: Union[str, Sequence[str], None] = '330213fbaf08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_tracked_products_product_id_fkey'), 'user_tracked_products', type_='foreignkey')
    op.drop_constraint(op.f('user_tracked_products_user_id_fkey'), 'user_tracked_products', type_='foreignkey')
    op.create_foreign_key(None, 'user_tracked_products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tracked_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tracked_products', type_='foreignkey')
    op.drop_constraint(None, 'user_tracked_products', type_='foreignkey')
    op.create_foreign_key(op.f('user_tracked_products_user_id_fkey'), 'user_tracked_products', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_tracked_products_product_id_fkey'), 'user_tracked_products', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
